spring:
  application:
    name: cityquest-backend
  datasource:
    url: jdbc:mysql://localhost:3306/cityquestdev
    username: admin
    password: adminpa55
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: false
    change-log: "classpath:/db/changelog/changelog-master.xml"

server:
  port: 8081

logging:
  level:
    caprita:
      catalin: DEBUG
